---
# This playbook installs and (re)configures Postgres

- name: Import PostgreSQL 9.5 GPG public key
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL 9.5 repository
  become: true
  command: echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql-pgdg.list > /dev/null

- name: Update apt with the PostgreSQL 9.5 repo
  become: true
  command: apt-get update -y

- name: install Postgres, its headers, and psycopg2
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - postgresql-9.5
    - postgresql-server-dev-9.5

- name: install psycopg2 from pip
  pip:
    executable: /usr/local/bin/pip
    name: psycopg2-binary

- name: add ckan_default database user
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB

- name: create ckan_default database
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    owner: "{{ db_user }}"
    template: template0

- name: create DataStore database
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ datastore_db }}"
    owner: "{{ db_user }}"

- name: set DataStore database owner
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ datastore_db }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: create DataStore database user
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ datastore_db_user }}"
    password: "{{ datastore_db_password }}"
