---
# This playbook configures CKAN

- name: initialise the database
  command: /usr/lib/ckan/default/bin/paster --plugin=ckan db init -c /etc/ckan/default/production.ini

- name: Set DataStore database permissions
  shell: /usr/lib/ckan/default/bin/paster --plugin=ckan datastore set-permissions --config=/etc/ckan/default/production.ini | sudo -u postgres psql --set ON_ERROR_STOP=1
