---
# This playbook installs an encrypt client
- name: Install the lets encrypt client
  git: repo=https://github.com/certbot/certbot.git dest=/opt/letsencrypt

- name: Create our client directory
  file: path=/etc/letsencrypt state=directory

- name: Put letsencrypt .ini in the correct place
  template: src=config/letsencrypt.ini dest=/etc/letsencrypt/cli.ini

- name: copy nginx config
  copy: src=config/nginx_ckan dest=/etc/nginx/sites-available/ckan mode=0644 owner=root

- name: Put shell script to run the lets encrypt in the right place
  template: src=config/letsencrypt-renew.sh dest=/usr/local/bin/letsencrypt-renew.sh

- cron:
    name: "auto renew lets encrypts"
    day: 1
    user: "root"
    job: "/usr/local/bin/letsencrypt-renew.sh"
