---
- name: install CKAN {{ version }} from git repository
  pip:
    editable: true
    name: git+https://github.com/ckan/ckan.git@ckan-{{ version }}#egg=ckan
    virtualenv: /usr/lib/ckan/default

- name: install CKAN python requirements
  become: true
  pip:
    requirements: /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default

- name: upgrade Database schema
  become: true
  command: /usr/lib/ckan/default/bin/paster --plugin=ckan db upgrade --config /etc/ckan/default/production.ini
