---
# This playbook installs and (re)configures Postgres.
- name: update apt-cache
  apt: update_cache=yes

- name: install Postgres and psycopg2
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql
    - python-psycopg2

- name: add ckan_default database user
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} role_attr_flags=CREATEDB

- name: create ckan_default database
  sudo_user: postgres
  postgresql_db: name={{ db_name }} encoding='UTF-8' owner={{ db_user }} template=template0
