---
# This role sets up lots of common packages used generally.

- name: install packages for CKAN
  become: true
  apt:
    state: installed
    update_cache: true
    pkg:
      - ack-grep
      - build-essential
      - emacs
      - git
      - htop
      - iotop
      - libmemcached-dev
      - libpq5
      - memcached
      - python-dev
      - python-virtualenv
      - redis-server
      - screen
      - tree
      - vim
      - zip
