---
# This role sets up lots of common packages used generally.

- name: install packages for CKAN
  become: true
  apt:
      pkg: "{{ item }}"
      update_cache: true
  with_items:
    - emacs
    - vim
    - htop
    # CKAN requirements
    - python-dev-is-python2
    - postgresql
    - libpq-dev
    - git-core
    - solr-jetty
    - openjdk-8-jdk
    - redis-server
