---
# This playbook installs and configures the backups

- name: create BOTO configuration
  template:
    src: config/boto.ini
    dest: /home/ubuntu/.boto

- name: create S3 configuration
  template:
    src: config/s3.ini
    dest: /home/ubuntu/.s3.ini

- name: backup requirements
  pip:
    name: requests
    version: 2.11.1
    virtualenv: /home/ubuntu/backup_env

- name: backup boto
  pip:
    name: boto
    version: 2.36.0
    virtualenv: /home/ubuntu/backup_env

- name: copy backup script
  template:
    src: scripts/backup.py.jinja2
    dest: /home/ubuntu/backup.py
    mode: 0744
    owner: ubuntu

- name: copy Python S3 uploader
  copy:
    src: scripts/upload.py
    dest: /home/ubuntu/upload.py
    mode: 0644
    owner: ubuntu

- name: copy restore script
  copy:
    src: scripts/restore.sh
    dest: /home/ubuntu/restore.sh
    mode: 0744
    owner: ubuntu

- name: copy Python S3 downloader
  copy:
    src: scripts/download.py
    dest: /home/ubuntu/download.py
    mode: 0644
    owner: ubuntu

- name: configure CRON
  cron:
    name: "run backup"
    hour: "1"
    minute: "1"
    user: "ubuntu"
    job: "/home/ubuntu/backup_env/bin/python /home/ubuntu/backup.py"
