---
# This playbook installs CKAN

- name: create CKAN lib directory
  become: true
  file:
    path: /usr/lib/ckan/default
    state: directory
    mode: 0755
    owner: ubuntu

- name: create CKAN etc directory
  become: true
  file:
    path: /etc/ckan/default
    state: directory
    mode: 0755

- name: create CKAN virtualenv
  become: true
  become_user: ubuntu
  command: virtualenv /usr/lib/ckan/default

- name: install an older setuptools for CKAN
  become: true
  become_user: ubuntu
  pip:
    name: setuptools
    version: 36.1
    virtualenv: /usr/lib/ckan/default

- name: install CKAN from git repository
  become: true
  become_user: ubuntu
  pip:
    editable: true
    name: git+https://github.com/ckan/ckan.git@ckan-2.7.2#egg=ckan
    virtualenv: /usr/lib/ckan/default

- name: install psycopg2
  become: true
  become_user: ubuntu
  pip:
    name: psycopg2
    version: 2.8.6
    virtualenv: /usr/lib/ckan/default

- name: remove ckan psycopg2
  become: true
  become_user: ubuntu
  lineinfile:
    state: absent
    line: psycopg2==2.4.5
    path: /usr/lib/ckan/default/src/ckan/requirements.txt

- name: install CKAN python requirements
  become: true
  become_user: ubuntu
  pip:
    requirements: /usr/lib/ckan/default/src/ckan/requirements.txt
    virtualenv: /usr/lib/ckan/default

- name: Add WSGI file
  become: true
  template:
    src: config/apache.wsgi
    dest: /etc/ckan/default/apache.wsgi

- name: link who.ini
  become: true
  file:
    src: /usr/lib/ckan/default/src/ckan/who.ini
    dest: /etc/ckan/default/who.ini
    state: link

- name: add production settings
  become: true
  template:
    src: config/prod_settings.ini
    dest: /etc/ckan/default/production.ini

- name: Ensure FileStore directory exists
  become: true
  file:
    path: /var/lib/ckan/default
    owner: www-data
    state: directory

- name: Ensure Apache can write to FileStore directory
  become: true
  acl:
    name: /var/lib/ckan/default
    entity: www-data
    etype: user
    permissions: u+rwx

- name: Ensure Ubuntu user can write to FileStore directory
  become: true
  acl:
    name: /var/lib/ckan/default
    entity: ubuntu
    etype: user
    permissions: u+rwx
