---
# This playbook installs the data directory

- name: install packages for repos
  become: true
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - php5
    - libapache2-mod-php5
    - php5-curl

- name: clone git repository
  git:
    repo: '{{ git_protocol }}github.com/nhsengland/datadirectory'
    dest: /home/ubuntu/datadirectory
    version: master

- name: copy apache2 config
  become: true
  template:
    src: config/apache2_ckan_default
    dest: /etc/apache2/sites-available/ckan_default.conf
    mode: 0644
    owner: root

- name: restart Apache
  become: true
  service: name=apache2 state=restarted

- name: delete nginx cache
  become: true
  file:
    path: /tmp/nginx_cache
    state: absent
