---
#
# Let's make ourselves a datapusher that isn't embarrassing.
#
- name: Kill the OKFN Datapusher
  file: path=/usr/lib/ckan/datapusher/src/datapusher
        state=absent

- name: Install backported Datapusher
  git: repo=https://github.com/nhsengland/datapusher
       dest=/usr/lib/ckan/datapusher/src/datapusher
       version=type_configuration

- name: Update backported Datapusher WSGI file
  template: src=config/datapusher.wsgi dest=/etc/ckan/datapusher.wsgi

- name: Configure the Datapusher
  template: src=config/datapusher_settings.py dest=/etc/ckan/datapusher_settings.py
