---
# This role installs pip for python 2 and virtualenv
- name: Remove system packaged pip
  become: true
  apt:
    name: python-pip
    state: absent

- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0440

- name: Install pip
  command: /usr/bin/python /tmp/get-pip.py
  become: true
  args:
    creates: /usr/local/bin/pip

# we install it with pip as the apt-get package has
# issues in the activate_this function used by wsgi.py
- name: Install virtualenv
  become: true
  pip:
    name: virtualenv
    executable: /usr/local/bin/pip
