---
# This role installs a current python 2 and modern packaging tools

- name: "Bootstrap Python 2"
  become: true
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python2-minimal)

- name: Remove outdated system packaged pip
  become: true
  apt:
    name: python-pip
    state: absent

- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0440

- name: Install pip
  become: true
  command: /usr/bin/python2 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip

- name: Ensure python package tools are up to date
  become: true
  pip:
    executable: /usr/local/bin/pip
    name: '{{ item }}'
    extra_args: '--upgrade'
  with_items:
    - pip
    - setuptools
