---
# This role sets the tools used for search
# This uses the instructions to work around
# running on jetty9 for ubuntu 20 from here
# https://github.com/ckan/ckan/issues/4762
# more succintly here
# https://pastebin.com/ejAMVpx3
- name: Create the directory for the jetty service
  become: true
  file:
    state: directory
    path: /etc/systemd/system/jetty9.service.d

- name: Create the solr service file
  become: true
  template:
    src: config/solr.conf
    dest: /etc/systemd/system/jetty9.service.d/solr.conf

- name: Update jetty host in start.ini
  become: true
  lineinfile:
    dest: /etc/jetty9/start.ini
    regexp: ^#jetty.host
    line: jetty.host=127.0.0.1

- name: Update jetty port in start.ini
  become: true
  lineinfile:
    dest: /etc/jetty9/start.ini
    regexp: ^jetty.port
    line: jetty.port=8983

- name: Update solr conf
  become: true
  template:
    src: config/solrconfig.xml
    dest: /etc/solr/solr-jetty.xml


- name: Move the default solr schema file
  become: true
  copy:
    remote_src: true
    src: /etc/solr/conf/schema.xml
    dest: /etc/solr/conf/schema.xml.bak

- name: Delete the original default solr schema file
  become: true
  file:
    path: /etc/solr/conf/schema.xml
    state: absent

- name: Symlink in the CKAN schema
  become: true
  file:
     src:  /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
     dest: /etc/solr/conf/schema.xml
     state: link

- name: Reload daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Restart Jetty
  become: true
  service:
    name: jetty9
    state: restarted

# note we cannot use retries and delay on the uri task
# because of the ansible version
- name: Pause for a few seconds to let it work
  pause:
    seconds: 3

- name: Check the appropriate url returns a 200
  uri:
    url: http://localhost:8983/solr/
