---
# This role installs and configures Apache and Nginx

- name: install Apache and Nginx configure Apache
  become: true
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - apache2
    - libapache2-mod-rpaf
    - libapache2-mod-wsgi

- name: remove default Apache site
  become: true
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Apache listen on port 8080
  become: true
  lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: "^Listen 80"
    line: "Listen 8080"
    state: present

- name: copy Apache vhost configuration
  become: true
  template:
    src: config/apache2_ckan_default
    dest: /etc/apache2/sites-available/ckan_default.conf
    mode: 664
    owner: root

- name: enable Apache vhost
  become: true
  file:
    src: /etc/apache2/sites-available/ckan_default.conf
    dest: /etc/apache2/sites-enabled/ckan_default.conf
    state: link

- name: restart Apache
  become: true
  service:
    name: apache2
    state: restarted

# Must happen after apache is configured
- name: install Nginx
  become: true
  apt:
    name: nginx
    state: installed

- name: add Launchpad's key ID
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14aa40ec0831756756d7f66c4f4ea0aae5267a6c

- name: add certbot PPA
  become: true
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: true

- name: install certbot
  become: true
  apt:
    pkg: python-certbot-nginx
    state: installed

- name: generate cert with Lets Encrypt
  become: true
  command: certbot certonly --nginx -n -d data.england.nhs.uk --agree-tos -m support@openhealthcare.org.uk

- name: copy nginx config
  become: true
  copy:
    src: config/nginx_ckan
    dest: /etc/nginx/sites-available/ckan
    mode: 0644
    owner: root

- name: deactivate default nginx site
  become: true
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: activate ckan nginx site
  become: true
  file:
    src: /etc/nginx/sites-available/ckan
    dest: /etc/nginx/sites-enabled/ckan
    state: link
