---
# This playbook deploys/installs a complete CKAN isolated instance for
# NHSEngland. Assumes a 64bit Ubuntu LTS as the target OS.

- name: Install Python 2 and modernise packaging tools
  gather_facts: false
  user: ubuntu
  hosts: webservers
  roles:
    - python

- name: Install common packages
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - common

- name: install and configure Postgres
  user: ubuntu
  hosts: dbservers
  roles:
    - database

- name: install and configure SOLR
  user: ubuntu
  hosts: search
  roles:
    - search

- name: install Apache and Nginx
  user: ubuntu
  hosts: webservers
  roles:
    - webservers

- name: install and configure CKAN
  user: ubuntu
  hosts: webservers
  roles:
    - install_ckan
    - plugins
    - datapusher
    - configure_ckan

- name: configure email
  user: ubuntu
  hosts: webservers
  roles:
    - email

- name: deploy data directory
  user: ubuntu
  hosts: webservers
  roles:
    - directory

- name: configure backup scripts
  become: true
  user: ubuntu
  hosts: dbservers
  roles:
    - backup

- name: restart services
  become: true
  user: ubuntu
  hosts: webservers
  tasks:
    - name: restart Jetty
      service:
        name: jetty8
        state: restarted

    - name: restart Apache
      service:
        name: apache2
        state: restarted

    - name: restart Nginx
      service:
        name: nginx
        state: restarted
