---
# This playbook deploys/installs a complete CKAN isolated instance for
# NHSEngland. Assumes a 64bit Ubuntu LTS as the target OS.

- name: Install common packages
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - common

- name: "Bootstrap Python 2"
  become: true
  hosts: all
  gather_facts: false
  user: ubuntu
  tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Modernise pip
  become: true
  user: ubuntu
  hosts: dbservers
  roles:
    - pip

- name: install and configure SOLR
  become: true
  user: ubuntu
  hosts: solr
  roles:
    - solr

- name: install Apache
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - apache

- name: install and configure Postgres
  become: true
  user: ubuntu
  hosts: dbservers
  roles:
    - db

- name: install CKAN
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - ckan

- name: install and configure DataStore
  become: true
  user: ubuntu
  hosts: dbservers
  roles:
    - datastore

- name: install and configure DataPusher
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - datapusher

- name: install and configure FileStore
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - filestore

- name: install plugin
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - plugin

- name: install adfs
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - adfs

- name: configure email
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - email

- name: configure S3 filestore
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - s3

- name: configure SSL
  become: true
  user: ubuntu
  hosts: webservers
  roles:
    - ssl

- name: configure ckan
  become: true
  user: ubuntu
  hosts: webservers
  tasks:
      - name: configure our CKAN instance
        template: src=config/prod_settings.ini dest=/etc/ckan/default/production.ini

      - name: initialise the database
        command: /usr/lib/ckan/default/bin/paster --plugin=ckan db init -c /etc/ckan/default/production.ini

      - name: Set DataStore database permissions
        command: /usr/lib/ckan/default/bin/paster --plugin=ckan datastore set-permissions -c /etc/ckan/default/production.ini postgres

      - name: restart Apache
        service: name=apache2 state=restarted

      - name: restart Nginx
        service: name=nginx state=restarted

- name: deploy data directory
  user: ubuntu
  hosts: webservers
  roles:
    - directory

- name: configure backup scripts
  become: true
  user: ubuntu
  hosts: dbservers
  roles:
    - backup
