---
#
# Playbook to deploy WIP to Test server.
#
- name: Deploy WIP changes
  vars:
    # PLEASE EDIT THIS BRANCH NAME AS APPROPRIATE.
    # BRANCHES ARE AWESOME.
    branch: ckan2.5
  hosts: webservers
  sudo: yes
  user: ubuntu
  gather_facts: false
  tasks:
    - name: Remove Legacy CKAN Extension
      file: path=/home/ubuntu/ckanext-nhsengland
            state=absent

    - name: Deploy NHS England!
      git: repo=https://github.com/nhsengland/ckanext-nhsengland
           dest=/home/ubuntu/ckanext-nhsengland
           update=yes
           version={{ branch }}
      notify:
        - Restart Apache

    - name: run setup.py for the plugin
      command: /usr/lib/ckan/default/bin/python setup.py develop
               chdir=/home/ubuntu/ckanext-nhsengland

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
