---
# This playbook sets up SSL.

- name: copy SSH/TLS configuration files
  sudo: yes
  user: ubuntu
  hosts: webservers
  tasks:
    - name: copy SSL certificate to correct location
      copy: src=config/data.england.nhs.uk.crt dest=/etc/ssl/data.england.nhs.uk.crt owner=root

    - name: copy SSL key to correct location
      copy: src=config/data.england.nhs.uk.key_secure dest=/etc/ssl/data.england.nhs.uk.key_secure owner=root

    - name: decrypt SSL certificate
      command: openssl rsa -in /etc/ssl/data.england.nhs.uk.key_secure -out /etc/ssl/data.england.nhs.uk.key -passin pass:{{ssl_passphrase}}

    - name: copy nginx config
      copy: src=config/nginx_ckan dest=/etc/nginx/sites-available/ckan mode=0644 owner=root

    - name: copy apache2 config
      copy: src=config/apache2_ckan_default dest=/etc/apache2/sites-available/ckan_default mode=0644 owner=root

    - name: restart Apache
      service: name=apache2 state=restarted

    - name: restart Nginx
      service: name=nginx state=restarted
