- name: update Plugins
  hosts: webservers
  sudo: yes
  user: ubuntu
  gather_facts: false
  tasks:
    - name: Update Git repo for ckanext-nhsengland
      git: repo={{ git_protocol }}{{ git_repos_nhse}} dest=/home/ubuntu/ckanext-nhsengland update=yes
      notify:
        - Restart Apache

    - name: Update Git repo for ckanext-adfs
      git: repo={{ git_protocol }}{{ git_repos_adfs}} dest=/home/ubuntu/ckanext-adfs update=yes
      notify:
        - Restart Apache


  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
