---
# Installs and configures SOLR for use by CKAN.
- name: update apt-cache
  apt: update_cache=yes

- name: install SOLR
  apt: pkg={{ item }} state=installed
  with_items:
    - solr-jetty
    - openjdk-8-jdk

- name: update SOLR configuration - NO_START
  lineinfile: 'dest=/etc/default/jetty8 regexp=^NO_START line="NO_START=0"'

- name: update SOLR configuration - JETTY_HOST
  lineinfile: 'dest=/etc/default/jetty8 regexp=^JETTY_HOST line="JETTY_HOST={{ solr_host }}"'

- name: update SOLR configuration - JETTY_PORT
  lineinfile: 'dest=/etc/default/jetty8 regexp=^JETTY_PORT line="JETTY_PORT={{ solr_port }}"'

- name: update SOLR configuration - JAVA_HOME
  lineinfile: 'dest=/etc/default/jetty8 regexp=JAVA_HOME line="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/"'

- name: copy solrconfig.xml
  template:
    src: config/solrconfig.xml
    dest: /etc/solr/conf/solrconfig.xml
    mode: 644
    owner: root
  notify: Restart Jetty
